elements:
  1:
    description: DAQ
    ip-address: null
    model: faster-daq
    number-of-inputs: 2
    parameters-config-file: faster_trunk.cfg
    part-of-channel-group: decision
    uid: 1
  2:
    connected-to: 1
    data-target: 1
    description: noname
    intro-target: rhb
    ip-address: 192.168.2.179
    model: syroco-amc
    parameters-config-file: syroco_amc_192.168.2.179.cfg
    state-target: 1
    trigger-target: 1
    uid: 2
  5:
    connected-to: 1
    data-target: 1
    description: noname
    intro-target: rhb
    ip-address: 192.168.2.185
    model: syroco-amc
    parameters-config-file: syroco_amc_192.168.2.185.cfg
    state-target: 1
    trigger-target: 1
    uid: 5
  8:
    connected-to: 2
    connected-to-slot: 1
    data-target: 2
    description: daughterboard A
    intro-target: rhb
    ip-address: 192.168.2.179
    model: caras-adc-trapezoid
    parameters-config-file: ch_1_2.cfg
    state-target: 1
    trigger-target: 1
    uid: 8
  9:
    connected-to: 8
    connected-to-slot: 1
    description: TRAPEZ_1
    model: caras-trapezoid-channel
    uid: 9
  10:
    connected-to: 8
    connected-to-slot: 2
    description: TRAPEZ_2
    model: caras-trapezoid-channel
    uid: 10
  11:
    connected-to: 2
    connected-to-slot: 2
    data-target: 2
    description: daughterboard B
    intro-target: rhb
    ip-address: 192.168.2.179
    model: caras-adc
    parameters-config-file: ch_3_4.cfg
    state-target: 1
    trigger-target: 1
    uid: 11
  12:
    connected-to: 11
    connected-to-slot: 1
    description: CRRC4_1
    model: caras-adc-channel
    uid: 12
  13:
    connected-to: 11
    connected-to-slot: 2
    description: CRRC4_2
    model: caras-adc-channel
    uid: 13
  14:
    connected-to: 5
    connected-to-slot: 1
    data-target: 5
    description: daughterboard A
    intro-target: rhb
    ip-address: 192.168.2.185
    model: mosahr-adc-trapezoid
    parameters-config-file: ch_5_6_7_8.cfg
    state-target: 1
    trigger-target: 1
    uid: 14
  15:
    connected-to: 14
    connected-to-slot: 1
    description: TRAPEZ_3
    model: mosahr-trapezoid-channel
    uid: 15
  16:
    connected-to: 14
    connected-to-slot: 2
    description: TRAPEZ_4
    model: mosahr-trapezoid-channel
    uid: 16
  17:
    connected-to: 14
    connected-to-slot: 3
    description: TRAPEZ_5
    model: mosahr-trapezoid-channel
    uid: 17
  18:
    connected-to: 14
    connected-to-slot: 4
    description: TRAPEZ_6
    model: mosahr-trapezoid-channel
    uid: 18
  19:
    connected-to: 5
    connected-to-slot: 2
    data-target: 5
    description: daughterboard B
    intro-target: rhb
    ip-address: 192.168.2.185
    model: mosahr-adc-crrc4
    parameters-config-file: ch_9_10_11_12.cfg
    state-target: 1
    trigger-target: 1
    uid: 19
  20:
    connected-to: 19
    connected-to-slot: 1
    description: CRRC4_3
    model: mosahr-crrc4-channel
    uid: 20
  21:
    connected-to: 19
    connected-to-slot: 2
    description: CRRC4_4
    model: mosahr-crrc4-channel
    uid: 21
  22:
    connected-to: 19
    connected-to-slot: 3
    description: CRRC4_5
    model: mosahr-crrc4-channel
    uid: 22
  23:
    connected-to: 19
    connected-to-slot: 4
    description: CRRC4_6
    model: mosahr-crrc4-channel
    uid: 23
interface:
  channel-views:
    button-groups:
      1:
        button-group-uid: 1
        contains-channel-groups:
        - 3
        - 2
        - 1
        - 0
        - 4
        description: Channel groups
        position:
        - 1
    channel-groups:
      0:
        channel-group-uid: 0
        contains-channels: []
        description: Channels
        position: !!python/tuple
        - 0
        - 0
      1:
        channel-group-uid: 1
        contains-channels:
        - 9
        - 10
        description: caras_trapez
        position: !!python/tuple
        - 1
        - 0
      2:
        channel-group-uid: 2
        contains-channels:
        - 12
        - 13
        description: caras_crrc4
        position: !!python/tuple
        - 2
        - 0
      3:
        channel-group-uid: 3
        contains-channels:
        - 15
        - 16
        - 17
        - 18
        description: mosahr_trapez
        position: !!python/tuple
        - 3
        - 0
      4:
        channel-group-uid: 4
        contains-channels:
        - 20
        - 21
        - 22
        - 23
        description: mosahr_crrc4
        position: !!python/tuple
        - 0
        - 1
    unassigned-channels: []
  config-type: 0
  data-output-dir: /home/fasxb/LaBr3/DAQ/../data
  datafile-no-date: false
  expert-trapez: true
  rhb-host: 192.168.0.1
  start-in-disk-mode: false
  t0-target: 192.168.2.185
  title: LaBr3
